# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5a086c1563ca5946998f307075ed757867de51be1ab3ad5545375fa9e5b55c02181141751509492e9b4fe947c175680675c94f6854aa8783fb0ae15827d39c78

test:
  secret_key_base: b290385bd3f11f07a594312601e3ad13c8cc1b291c6e9ad38f345d1527c870caeba509418883cb4ab523578ea962c8bf23ece88fc9b9f3f895b32bb62a632352

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
